name: Create Pull Request for Release Branch
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: |
          pr_list=$(gh pr list --base "$BASE_REF" --json number --jq '.[] | .number')
          if [ -n "$pr_list" ]; then
            gh pr create --fill --draft --base live
          else
            echo "Pull request for branch $BASE_REF already exists"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_REF: ${{ github.base_ref }}